services:
  failover-gateway:
    image: hhftechnology/failover-newt-tc:latest
    # ADD THESE PERMISSION SETTINGS
    privileged: true  # Gives full access to host devices - CRITICAL for TUN
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    security_opt:
      - apparmor:unconfined  # Disable AppArmor restrictions
    sysctls:
      - net.ipv4.ip_forward=1  # Enable IP forwarding
    environment:
      # Core Configuration
      - ENABLE_FAILOVER=true
      - FAILOVER_MODE=immediate
      - PRIMARY_SERVICE=newt
      
      # Health Check Configuration
      - HEALTH_CHECK_INTERVAL=10
      - HEALTH_CHECK_TIMEOUT=5
      - HEALTH_CHECK_FAILURES_THRESHOLD=3
      - HEALTH_CHECK_RECOVERY_THRESHOLD=5
      
      # Newt Configuration
      - NEWT_ID=${NEWT_ID}
      - NEWT_SECRET=${NEWT_SECRET}
      - PANGOLIN_ENDPOINT=${PANGOLIN_ENDPOINT}
      - ENABLE_NEWT=true  # ADD THIS LINE - Explicit enable for Newt
      
      # Tailscale Configuration
      - TAILSCALE_AUTH_KEY=${TAILSCALE_AUTH_KEY}
      - TAILSCALE_HOSTNAME=failover-gateway
      - TARGET_PORTS=80,3000,8080
      - TAILSCALE_ACCEPT_DNS=true
      - TAILSCALE_ACCEPT_ROUTES=false
      - TAILSCALE_ADVERTISE_EXIT_NODE=false
      # IMPORTANT: Must advertise the same subnet that Newt connects to
      - TAILSCALE_ADVERTISE_ROUTES=${TAILSCALE_ADVERTISE_ROUTES:-10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      
      # Notification Settings (optional)
      - ENABLE_NOTIFICATIONS=false
      #- NOTIFICATION_WEBHOOK=https://your-webhook-url.com
    volumes:
      - ./data/tailscale:/var/lib/tailscale
      # ADD THIS LINE - Mount host kernel modules
      - /lib/modules:/lib/modules:ro
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "9095:9090" # Status dashboard
    restart: unless-stopped
    networks:
      - frontend
    
    # ADD THIS HEALTHCHECK
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  webapp:
    image: nginx:alpine
    container_name: app  # ADD THIS LINE - Fixed name for DNS resolution
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    driver: bridge